title: Jesús Checa
description: Informática y tecnología. Web personal

author: 
    name: Jesús Checa
    twitter: jesustxk

repository: jesustxk/jesustxk.github.io

twitter:
    username: jesustxk

social:
    name: Jesús Checa
    links:
        - https://twitter.com/jesustxk
        - https://github.com/jesustxk

encoding: UTF-8
lang: es_ES
    
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-github-metadata

exclude:
   - Gemfile
   - Gemfile.lock
   - node_modules
   - vendor
   - README.md
