title: Jesús Checa
description: Informática y tecnología. Web personal

author: Jesús Checa

repository: jesustxk/jesustxk.github.io

twitter_username: jesustxk
github_username: jesustxk
email: jesustxk@gmail.com

social:
    name: Jesús Checa
    links:
        - https://twitter.com/jesustxk
        - https://github.com/jesustxk

encoding: UTF-8
lang: es_ES
    
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-github-metadata

exclude:
   - Gemfile
   - Gemfile.lock
   - node_modules
   - vendor
   - README.md
